name: Terraform CI CD Pipeline for Deploying AWS Resources
run-name: ${{ github.actor }} has triggered the pipeline

on:
  push:
    branches:
      - 'main'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  build-infra:
    name: terraform-ci-cd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Checkov (Terraform security scan)
        uses: bridgecrewio/checkov-action@master
        with:
          directory: Lab2/Task1/Terraform

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: Lab2/Task1/Terraform

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: Lab2/Task1/Terraform

      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: Lab2/Task1/Terraform

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        working-directory: Lab2/Task1/Terraform